/**
 * Lending Domain Types
 *
 * TypeScript interfaces and enums for the Lending feature.
 * Represents the complete domain model for lending items.
 *
 * Feature: 009 - Lending Tracker
 * Architecture: Layered (UI → Service → Repository → SQLite)
 */

/**
 * Lending Status Enum
 *
 * Represents the state of a lending record.
 * - ACTIVE: Item is currently lent out to borrower
 * - RETURNED: Item has been returned by borrower
 */
export enum LendingStatus {
  ACTIVE = 'ACTIVE',
  RETURNED = 'RETURNED',
}

/**
 * Lending Domain Entity
 *
 * Represents a single item lent to someone.
 * This is the complete, hydrated object returned from the database
 * after all operations (create, read, update).
 *
 * Attributes:
 * - id: Unique identifier (UUID generated on creation)
 * - item_id: Reference to the item being lent (foreign key)
 * - borrower_name: Name of person borrowing the item (required)
 * - note: Optional context about the lending
 * - lent_at: Timestamp when lending was created
 * - returned_at: Timestamp when item was returned (null if still ACTIVE)
 * - status: Current state of the lending (ACTIVE or RETURNED)
 * - created_at: Record creation timestamp
 * - updated_at: Record last modification timestamp
 */
export interface Lending {
  id: string; // UUID
  item_id: string; // UUID (foreign key)
  borrower_name: string; // Required
  quantity: number; // Number of units lent
  note?: string; // Optional
  lent_at: Date;
  due_date: Date | null; // Optional return-by date
  returned_at: Date | null;
  status: LendingStatus;
  reminder_id?: string; // Scheduled notification identifier
  created_at: Date;
  updated_at: Date;
}

/**
 * Lending Creation Input DTO
 *
 * Data Transfer Object for creating a new lending.
 * Only accepts the fields that users provide;
 * timestamps and IDs are generated by the system.
 *
 * Used by:
 * - LendingService.createLending()
 * - UI form submission handlers
 */
export interface LendingCreateInput {
  item_id: string;
  borrower_name: string;
  quantity?: number;
  note?: string;
  due_date?: Date | null; // Optional due date
}

/**
 * Lending Return Input DTO
 *
 * Data Transfer Object for marking a lending as returned.
 * Minimal: only the lending ID needed.
 *
 * Used by:
 * - LendingService.markAsReturned()
 * - UI return confirmation handlers
 */
export interface LendingReturnInput {
  id: string; // Lending ID to mark as returned
}

/**
 * Lending Query Filter
 *
 * Optional filter for querying lendings.
 * Allows filtering by status and item.
 *
 * Used by:
 * - Repository query methods (optional)
 * - UI filtering (optional for future enhancement)
 */
export interface LendingFilter {
  status?: LendingStatus; // Filter by ACTIVE/RETURNED
  item_id?: string; // Filter by specific item
}

/**
 * Lending List Response
 *
 * Standard response structure for list queries.
 * Includes the lending data with associated item context.
 *
 * Used by:
 * - LendingService.getActiveLendings()
 * - LendingService.getAllLendings()
 */
export interface LendingWithItemContext extends Lending {
  // Extended with item details at service layer
  item?: {
    id: string;
    name: string;
    space_id?: string;
    space_name?: string;
    container_id?: string;
    container_name?: string;
  };
}

/**
 * Service Error Response
 *
 * Standard error thrown by LendingService.
 * Always has code and message for consistent error handling.
 *
 * Example codes:
 * - 'ITEM_NOT_FOUND'
 * - 'INVALID_BORROWER_NAME'
 * - 'DUPLICATE_ACTIVE_LENDING'
 * - 'LENDING_NOT_FOUND'
 * - 'INVALID_STATUS_TRANSITION'
 * - 'DATABASE_ERROR'
 */
export interface ServiceError {
  code: string; // Machine-readable error code
  message: string; // User-friendly error message
}
